# Best Practices for Dissemination to Scientific and Lay Audiences {#Dissem}

<center>
*Lydia HaRim Ahn (she/her/hers), Arizona State University*\
*Melissa K. Holt (she/her/hers),Boston University*\
*Lisa De La Rue (she/her/hers), University of San Francisco*\
*Tanvi N. Shah (she/her/hers), Boston University*\
*The University of San Francisco resides on the traditional homelands of the Ramaytush Ohlone (pronounced rah-my-toosh oh-loh-nee) tribal nation. We acknowledge the painful history of genocide and forced removal from this territory, and we celebrate the public presence of Ohlone descendants who are working today to preserve and nourish their indigenous identity.*\

*We (Melissa and Tanvi) acknowledge that the territory on which Boston University stands is that of The Wampanoag and The Massachusett People. Our classroom and BU’s campus are places to honor and respect the history and continued efforts of the Native and Indigenous community leaders which make up Eastern Massachusetts and the surrounding region. This statement is one small step in acknowledging the history that brought us to reside on the land, and to help us seek understanding of our place within that history. Ownership of land is itself a colonial concept; many tribes had seasonal relationships with the land we currently inhabit. Today, Boston is still home to indigenous peoples, including the Mashpee Wampanoag and Wampanoag Tribe of Gay Head (Aquinnah). For more information, please visit the [North American Indian Center of Boston](http://www.naicob.org/) and the [Commission on Indian Affairs of the State of Massachusetts](https://www.mass.gov/service-details/indian-affairs).*\

*I (Lydia Ahn) acknowledge the 22 Native Nations that have inhabited this land for centuries. Arizona State University’s four campuses are located in the Salt River Valley on ancestral territories of Indigenous peoples, including the Akimel O’odham (Pima) and Pee Posh (Maricopa) India Communities, whose care and keeping of these lands allows us to be here today.*\ 
</center>
<br>

The focus of this chapter is on dissemination of research findings, geared toward those in the field of psychology. The chapter first reviews the importance of dissemination and then describes ways in which researchers disseminate their findings to scientific and lay audiences, with attention to culturally responsive and equitable dissemination practices. The chapter closes with recommendations for best practices in dissemination. 

## Learning Objectives

Learning objectives for this chapter include the following:

* Describe examples of best practices in dissemination
* Discover ways to disseminate research for scientific and lay audiences, with a lens toward considering ways to amplify research that centers on dismantling oppressive practices and includes voices from marginalized groups
* Learn practical recommendations for enhancing dissemination tailored to specific audiences and formats 

## Recommended Readings and Resources

The following served as central references in the development of this chapter and are valuable  resources for academics interested in bolstering their dissemination efforts.

* Ashcraft, L. E., Quinn, D. A., & Brownson, R. C. (2020). Strategies for effective dissemination of research to United States policymakers: A systematic review. *Implementation Science*, 15(89). https://doi.org/10.1186/s13012-020-01046-3
* Sommer, R. (2006). Dual dissemination: Writing for colleagues and the public. *American Psychologist*, 61(9), 955-958. https://doi.org/10.1037/0003-066X.61.9.955
  - This article reviews both scientific writing and writing for the public. 
* [The Campbell Collaboration](https://www.campbellcollaboration.org): 
  - The Campbell Collaboration, a social science research network, provides open source and policy-relevant syntheses, many of which include plain language summaries of research goals and results.
* [Community Tool Box](https://ctb.ku.edu/en/table-of-contents/participation/promoting-interest). (2022). *Chapter 6: Communications to promote interest*. 
  - This tool box offers in-depth guidance on developing and tailoring a communication plan for a general application.
* Schroeder, S., & Bauman, S. (2019, Aug). *Dissemination of rural health research: A toolkit*. Rural Health Research Gateway. 
  - This document, focused on rural health research, provides individuals with a set of resources to help package and disseminate research findings. Additionally, this document describes multiple modes of information dissemination and offers examples, which could be applicable to other areas of research. 
 
  
## Importance of Dissemination 
Psychologists who engage in research are often under pressure to publish manuscripts in peer-reviewed journals and present at academic conferences, an experience that is similar across academic disciplines. More recently, other outlets–such as Twitter–have also become key points of dissemination for researchers. Indeed, only a few years after the launch of Twitter, one in four academics began to use Twitter (Priem et al., 2012) as a platform to disseminate their research, engage in virtual conversations around scholarship, and disseminate their research to broader audiences. Platforms such as Twitter, along with changes in the open access publishing space, have resulted in the general public having more access to research findings, which historically had been restricted to those with access to university library systems. There have also been renewed conversations regarding optimal ways of disseminating research, including to scientific audiences, lay audiences, and other specific audiences (e.g., schools, U.S. policy makers; [@ashcraft_strategies_2020; @baker_dissemination_2021]. In this chapter, we focus specifically on research dissemination for scientific and lay audiences, with attention to culturally responsive practices and considerations. 

## Research Dissemination for Scientific Audiences        
Historically, research has been designed for scientific audiences, such as other researchers, students, and faculty. Typically, academic psychologists are considered to be strong scientific communicators when they publish journal articles, write books, present at psychological conferences, receive grants or serve as advisors on grants, and serve on governing bodies of psychology organizations [@garvey_scientific_1965]. Further, in graduate school, students are trained to achieve these goals, from learning how to effectively engage in scientific writing [@sommer_dual_2006] to how to write in a way that is understandable to academic audiences [@lewis_communicating_2021]. Similarly, graduate students, faculty, and researchers attend regional, national, and international conferences to share their own research findings and learn from others’ research through presentation modalities such as posters, roundtables, and symposia. Attendance at key conferences such as the American Psychological Association’s (APA) Annual Conference is high; over 12,000 individuals attended APA in 2019 (APA, 2019). 

While publications, books, and conferences have been the main sources of research dissemination to scientific audiences, existing barriers can limit the reach of scientific findings to other researchers. For example, if an independent researcher outside of the academic community would like to conduct research, they may have trouble accessing scientific articles without a database. In addition, some universities may not pay for specific databases or journals. An international scholar may struggle to find literature without access to certain databases at their university. A parent on parental leave may not have the time, energy, or resources to attend an in-person conference without consideration of their family needs. In addition, the review and publication process can be lengthy, making it challenging for research to be disseminated in a timely manner. To address some of these barriers, there has been an increase in quicker and accessible methods of dissemination, such as open science practices like pre-prints. 

One method for rapid dissemination that has become increasingly prevalent is the use of pre-prints. The Public Library of Science (PLOS) is a public server that allows researchers to post their manuscripts before they are published. This allows for others to read, provide feedback, and cite pre-prints in their work. Relatedly, open science  practices highlight the importance of transparent, shared scientific research that makes research accessible to everyone. It creates knowledge freely accessible to everyone and can be useful for building scientific communities and collaboration [@fecher_open_2013]. The “publish or perish” culture refers to the academic pressures of publishing so that faculty members may gain tenure [@de_rond_publish_2005]. Open science aims to be more equitable by enhancing collaboration through data sharing, transparency, and an orientation toward the public for recognizing the importance of the work rather than gatekeepers of science [@matsick_bridging_2021]. Piwowar and colleagues [-@piwowar_state_2018] examined the prevalence and impact of open access publications, and they found that 27.9% of publications are in open access outlets, and notably, open access articles are cited more frequently. While there are numerous benefits to open access publications from the point of view of the reader, there are also challenges, particularly around equity. For instance, given the costs charged to authors for publishing in open access sources, this restricts who is able to do so and also may skew authors from high-income countries to publish open access publications [@smith_decolonizing_2021].

Buchanan and colleagues [-@buchanan_upending_2021] highlight the pervasiveness of racism and White  supremacy in research dissemination. In turn, they provide strategies to dismantle systems of oppression in psychological science. For example, they note the importance of language, which can often perpetuate stereotypes towards People of Color. While APA now requires the reporting of race and ethnicity in research articles, Buchanan and colleagues [-@buchanan_upending_2021]  provide additional recommendations for researchers. For instance, they advocate for using systems-centered language that discusses the roots of health inequities, selecting inclusive journal keywords, defining race contextually and conceptually (i.e., naming that race is a social construct), reporting ethnicity (not only race) of all participants, and highlighting variability among people of color. In addition to practical recommendations when writing articles for scientific communities, Buchanan and colleagues [-@buchanan_upending_2021]  also suggest to “promote the visibility of BIPOC scholarship” via website spotlights or Twitter posts (p. 7). To do this, it would be useful for journals to require positionality statements, or the researchers’ worldview and the position that they take in research in research articles [@darwin_holmes_researcher_2020; @savin-baden_qualitative_2023], in order to showcase diversity in journals. There is also a need for methods to disseminate information to BIPOC communities, such as having practice-oriented, open-access journals that provide research findings in a digestible way, use popular platforms like social media networks or newsletters to disseminate research to the communities who would benefit from the information, and collaborate with community partners in the research and dissemination processes. 

Finally, scholars in the academic community also are utilizing “Academic Twitter” as a space to disseminate their research findings. With the development of social media, this allows for researchers to share their research in more accessible ways. As dissemination through platforms such as Twitter continue to progress, journal editors should also be reflective and intentional about the articles they choose to spotlight and should consider utilizing social media to highlight articles that focus on decolonizing and uprooting systemic oppression within the field of psychology. This extends to articles spotlighted through other avenues as well, including list-servs.


## Dissemination to the Public 
Traditionally, research has been heavily confined to academic and formal scholarly spaces with the dissemination of work primarily focused on reaching other researchers. While dissemination to other scholars is an important consideration that allows for the continued refinement and generation of theories and interventions, this inherently limits the impact of work. Sommer [-@sommer_dual_2006] stressed the importance of dual dissemination, noting that it is critical for psychologists to write articles for both academic journals and for the public. Indeed many researchers engage in their work with a greater vision of helping to address a societal-level concern or striving to improve the lives of others. In order to fully realize this hope, information needs to get to the people who will actually use it in the real world. 

Public dissemination can take many different formats. One helpful approach is to translate scholarly or academic works into plain language summaries or briefs. The [Campbell Collaboration](https://www.campbellcollaboration.org) is a social science research network that provides open source and policy-relevant evidence syntheses (e.g., systematic analyses). Many of these syntheses also include plain language summaries, which capture the goal and results of the research in comprehensible language that can be understood by individuals from non-academic backgrounds. Science communication (i.e., SciComm) is a promising area of research that emphasizes the importance of communicating science to others. However, there are multiple trainee, mentor, and institutional barriers that make it challenging to teach and mentor trainees on scientific communication [@anderson_mentoring_2022]. Despite these barriers, providing presentations at schools, community clinics, or neighborhood events are other examples of dissemination that can allow the public access to research findings. These spaces will allow for dialogue around the issues that are relevant to the particular space and give the researcher an opportunity to share how their work might support the needs of the community.

The knowledge and learnings from research should be shared with the communities in which it was generated, and in language that is accessible and clear. The work should be disseminated back to people in a culturally appropriate way [@smith_decolonizing_2021]. There are two ways that this can be done as described by Smith (2021). The first is “reporting back,” which includes sharing the results of the research with the community. This may occur in the form of a ceremony, providing copies of the work to participants that can be read out loud, or in the form of symposia or presentations in local community settings. The second way is by “sharing knowledge.” While it may feel easier to hand out a report and resist continued dialogue, it is the latter that can have the most meaningful impacts. Researchers should share the theories and analyses which have informed the work and engage in dialogue with the community about what was identified in the research. This process of sharing knowledge also encourages the researchers to be open to different perspectives and other ways of thinking about the research topic and to lean into the valuable knowledge that the community can share. 

Lastly, dissemination of research can also be a form of advocacy and action. DeBlaere and colleagues [-@deblaere_social_2019] suggest that counseling psychologists can engage in dissemination to advance social justice and change public attitudes. For example, psychologists and students could write op-eds, use social media, develop toolkits focused on social justice, and conduct workshops in the community. Although op-eds have the ability to reach a broader audience, there continue to be challenges with disincentivizing scholars to engage in public writing [@deblaere_social_2019]. Thus, institutional structures and training programs should consider ways to reward dissemination to the public and community [@buchanan_upending_2021]. In conclusion, disseminating research can be a critical method in advocating for marginalized communities and to raise critical consciousness [@fassinger_toward_2013].  

## Summary, Conclusions, and/or Recommendations

In summary, some key recommendations with respect to dissemination are to:
1.	Encourage open science practices.
2.	Establish the use of pre-prints as standard practice.
3.	Increase the spotlight on open-access journals.
4.	Promote publishing in practice-oriented journals that provide research findings in a digestible way.
5.	Make it the norm to translate scholarly or academic works into plain language summaries or briefs.
6.	Utilize social media to highlight articles that focus on decolonizing and uprooting systemic oppression within psychology.
7.	Support reflexive thinking about articles spotlighted on list-servs.
8.	Collectively push towards rewarding dissemination to the public and community.
9.	Include practical recommendations when writing articles for scientific communities.
10.	Hold presentations at schools, community clinics, or neighborhood events to disseminate research findings to a larger audience.

## Suggestions for Practice, Further Learning, and/or Conversation

From this chapter, we recommend some suggestions to further practice dissemination of research for both scientific audiences and to the public. For example, researchers may consider learning open science practices. The Open Science Framework (OSF) has resources about pre-registration and additional webinars and instructions with examples. Researchers may also benefit from translating a research article to a tangible product, such as a brochure, public health flyer, presentation to the community, Twitter/Instagram/Tiksok, op-ed, or social media post, depending on the audience. For example, resources such as this [LinkedIn article](https://www.linkedin.com/advice/1/how-do-you-use-social-media-promote-your-research-findings)on using social media to promote research findings can help researchers translate their research findings to the public. Using interpersonal communication strategies, such as first person pronoun-rich captions, using selfies, and two-way conversations, can encourage greater conversations about science on social media [@martin_using_2020]. Lastly, a systematic review about communicating science to the public suggests avoiding jargon, including citations, using neutral language, highlighting open science, being mindful about uncertainty, and being mindful about structuring texts [@konig_how_2024].  

## References
