# Social and Cultural Responsivity in the Research Environment: Graduate Student Perspectives and Recommendations {#Environ}

<center>
*Sally D. Stabb, Ph.D. (she/her), Marlene Williams, Ph.D. (she/her)*\
*& Oluwatosin Akintan, M.Ed. (she/her)*\
*Texas Woman’s University*\
*Texas Woman’s University is on the lands of the Tawakoni, Wichita, Kiikaapoi (Kickapoo) and Numunuu Sookobitu (Comanche) peoples.*\
</center>
<br>

Follow this [screencasted lecture link](https://youtu.be/rS_Y-RMS2c8) for an accompanying lecture on the topic. 

The focus of this chapter is on developing social and cultural responsivity in the research environment in graduate programs. 

## Learning Objectives

Learning objectives for this chapter include the following:

* Identify challenges that graduate students with minoritized identities face in the context of academic research enviornments. 
* Identify potential structural changes that could be implemented by faculty or administrators to enhance the research environment for  graduate students with minoritized identities.
* Explore how elements such as institutional culture, mentorship dynamics, resource availability, and collaborative opportunities impact students' journeys through research programs.

## Recommended Readings and Resources

The following served as critical references in the development of this chapter. We encourage you to review them.

* Buchanan, N. T., Perez, M., Prinstein, M. J., & Thurston, I. B. (2021). Upending racism in 
psychological science: Strategies to change how science is conducted, reported, 
reviewed, and disseminated. *The American Psychologist, 76*(7), 1097–1112. https://doi-org.ezp.twu.edu/10.1037/amp0000905
  - This article provides a concise, compelling, and thorough tour through the process of research production and publishing with specific implications/recommendations for anti-racist psychological science. 
* Perez-Lopez E, Gavrilova L, Disla J, Goodlad M, Ngo D, Seshappan A…..Berhe, A. A. (2022) Ten simple rules for creating and sustaining antiracist graduate programs. *PLoS Computational Biology, 18*(10), 1-11.  e1010516. https://doi.org/10.1371/journal.pcbi.1010516
  - Both direct and accessible, this article provides a great list of actions that can be taken by multiple constituencies involved in the endeavor that is graduate school. Recommendations can easily be applied to the specifics of the graduate research environment.  
* Marker, M. (2019). Indigenous knowledges, universities, and alluvial zones of paradigm change. *Discourse* (Abingdon, England), 40(4), 500-513. https://10.1080/01596306.2017.1393398
  - This resource provides a thorough critique of the limiting confines of traditional White-centric research culture and personal accounts of the unique impacts on American Indian graduate students, a population that is typically overlooked.
* Brown, E. M., & Grothaus, T. (2021). Interracial Trust between Black Doctoral Student Protégés and White Mentors. *International Journal of Multicultural Education, 23*(2), 70–87. https://doi.org/10.18251/ijme.v23i2.2613
  
## An IRB Story 

The following is a personal account of an adverse research experience that Assistant 	Professor Dr. Williams (second author of this chapter) endured while chairing a doctoral student’s dissertation. The case example serves to illuminate the lived experiences of marginalized faculty and students who are engaging in research on marginalized populations and the various ways that biases in academic research culture can impact them. 
	
>I was chairing a dissertation that was a mixed-methods study broadly exploring the perinatal mental health of Black women in the U.S. Both researchers identified as Black women with research expertise on Black women’s mental health and intersectionality theory. Given this extensive research experience on Black women, both were aware of the potential pushback on this kind of research. 
	
>Though within my current counseling psychology program I had not experienced strong bias towards my research, I have had adverse experiences in the past, which have contributed to a certain level of hypervigilance to protect my research from being watered-down or overpowered by White voices and a felt sense to continuously justify why my research on Black women is imperative to the academy and beyond. Due to these past experiences in predominantly White academic spaces, I was feeling especially protective in my role as research mentor to a young Black woman. I often engaged in a delicate balance between allowing her autonomy and modeling how to address potential push-back we may experience with this project. Thus, upon the inception of her dissertation topic, both myself and Kesha had numerous discussions about how to address potential biased perspectives of research on this vulnerable population of Black women surrounding their perinatal mental health. We were cognizant of the medical racism and mis-conceptualizations of Black women having a higher pain tolerance and not getting quality medical care in comparison to their White counterparts. We were aware of the ways in which racism in medical settings have contributed to the higher rates of maternal mortality among Black women. We were aware that forms of gendered racial discrimination could be directed at us as Black women researchers in the field of psychology. After having the draft approved by her dissertation committee at her dissertation defense we submitted an IRB application. Given the intimate nature of this research topic and the researchers’ training in counseling psychology, after the dissertation defense and while preparing the IRB application, we carefully considered how to ethically engage in our roles as researchers with these participants. 

>After submitting the IRB application and receiving a lot of questions from the IRB, we requested to meet with the IRB to discuss. The IRB requested major edits to how we would address potential ethical concerns, which in and of itself is a very typical and normal step in the IRB process. However, during this meeting I quickly realized that this was not a collaborative safe space for us to collectively identify effective ethical approaches to our research on Black women. Instead, members of the IRB who identified as White women, reprimanded us for a lack of consideration of this at-risk population. Ironically, this is exactly what myself and the student spent months doing, not to mention our own aforementioned internal hypervigilance of protection over this population. This was not considered by the IRB as they continued to press us with questions from vantage points that demonstrated their biased assumptions that we were careless in research protocol. We were talked over and not invited to share our perspective. I could feel my face getting hot and my heart pounding and I internally vacillated between states of feeling hopeless for our research project and feeling forced to justify my credibility as a researcher, again. After sifting through these emotions, firmly justifying our careful consideration of gendered racism experienced by this population, and somehow calmly coming to an agreement on the next steps for the IRB, we ended the call and I debriefed with the dissertation student about what we had just experienced. 

>There were layers of power dynamics in that meeting that perpetuated the rigid Westernized conceptualization of knowledge that has historically excluded the voices and realities of Black women. Though we have persisted and are continuing this research project, this adverse experience has increased my pre-existing sense of protection over research by and on Black women. This experience was a reminder to me that when doing research with Black women there is always this feeling like you’re holding your breath while never really feeling like you can fully and safely settle into the research you are doing for the unspoken reality that it will be subjected to gendered racial biases and poked and prodded at throughout  the research process. Essentially, as a Black woman researcher, you hold an awareness of the gendered racism you experience as the researcher and the gendered racism the Black woman population that you are studying experiences as well. In this example, and as will be discussed in later sections of this chapter, the research climate was impacted by bias held by gatekeepers of research protocol, which can contribute to less production of research on marginalized populations and the continued underrepresentation and silencing of BIPOC voices in graduate research.


## Purpose and Overview         

We are writing this chapter because the IRB stories - and countless other research stories like them - continue to happen. We would like to be part of changing that. While this open access text is primarily intended as an exploration of methodological options for researchers, the research culture and context in which these methods must inevitably be situated all too often remains a source of frustration, isolation, conflict, and despair [@hall_falling_2022; @maton_experiences_2011; @miller_values_2020]. The academic research environment in which graduate students and faculty are immersed is deeply entrenched in White, middle-class/owning class, Eurocentric, patriarchal, heterosexist and cis-normative values and structures [@ajjawi_what_2018; @buchanan_upending_2021; @okun_white_2021; @perez-lopez_ten_2022; @posselt_rigor_2018; @talusan_identity-conscious_2022; @tung_making_2023; @watkins_engaging_2018]. This means that graduate students and faculty with minoritized identities are constantly having to grapple with both subtle and blatant challenges not just to the research they may want to do, but to their very personhood. Doing research could be a joyous, emotionally moving, intellectually fascinating, and relevant experience, in which we reveal new knowledge, elevate the voices of those who have been unheard, and facilitate social change. While research will always have challenges, the environment of our programs and universities should not be one of them; we provide recommendations towards that end.

The chapter is structured to initially provide a short historical context for the research environment for graduate students. This will include naming the often hidden norms and values of academia as a white supremacist organization [@dancy_historically_2018; @okun_white_2021; @perez-lopez_ten_2022], as well as discussing the traditional predictors of success in graduate school with attention to their failures, particularly for minoritized students [@ajjawi_what_2018; @feldon_predictive_2024; @gittings_doctoral_2018; @kis_leaving_2022; @kurysheva_once_2022]. Concise/selected summaries of the literature on graduate school stressors (e.g. @cho_under_2021 ) and on mentoring (e.g. [@hall_falling_2022; @kim_putting_2021; @mangione_mentoring_2018; @cirillo-mccarthy_developing_2022] are also included as a jumping off point for later recommendations. Following that, we focus on the direct experiences of minoritized graduate students, primarily drawing from the qualitative literature in which their voices and words are showcased. Themes from this literature are summarized. The chapter concludes with a synthesis of concrete actions to improve the research culture for minoritized graduate students and faculty.

A note on language: We use identity terms such as “Black” or “LGBTQ” in the body of our chapter as they are  commonly used in research and in everyday language and such usage is generally accepted as appropriate and respectful. However, we also acknowledge that identities can be a personal and self-identified matter. We recognize that not everyone may identify with the identity language we are using even though they may have an ancestry, appearance, or geographic origin that might be associated with said identity. Therefore, we have chosen headings that reflect that capacity for choice and self-determination.  


## Research Culture: History and Context

While research may occur in many settings (corporate, non-profit, governmental etc.), it is arguably at university where researchers are first forged. Universities in the U.S. have their origins in settler colonialism [@dancy_historically_2018], the intentional process of emigrating in order to acquire wealth and to establish new communities by subjugating indigenous peoples and their culture.  European White colonizers defined themselves superior to all other races, thereby justifying their taking of land as well as the enslavement, if not outright extermination, of people of color (POC). They also instituted a host of socio-political and economic processes too numerous to detail here which further served to privilege Whites and disenfranchise Blacks and other people of color. As Dancy et al. [-@dancy_historically_2018] state, “the explicit function of the university was to operate within (and in service to) the new colonial establishment…Created to educate the offspring of colonizers, the colonial university acted as a preserver of social inequality by only serving White ‘elite’ males” (p.182). The legacy of those origins is still much in evidence. 

White cultural values and norms remain prominent in universities as a whole and in the research training environment in particular. 
Okun [-@okun_white_2021] powerfully articulates the nature of White supremacy culture in organizations such as academia. Two key aspects of that culture are perfectionism and individualism, such as believing there is only one right way to do things, that you must figure out everything correctly on your own, or that you’re the only one who really knows how to do X or Y. The competitive component of individualism results in an emphasis on progress being equated with more production, hoarding of information and power, overwork, and time pressure. In addition, the legacy of White European ways results in elevating the written word over all other forms of communication and messages to restrict emotionality in order to be “objective.” White supremacy culture is evident when persons in power believe they have the right to remain comfortably unchallenged, are defensive about racism, and engage in paternalistic practices. 

Multiple aspects of the research process are embedded in these values and norms. From the requirement for the dissertation being an as-close-to-perfect-as-possible individual product; to the insistence on White comparison samples in research examining Black, Indigenous, and other People of Color  (BIPOC); to the dearth of research on minoritized persons in general, to the lack of representation of marginalized persons as journal reviewers and editors; the legacy of universities’ White colonial past persists [@buchanan_upending_2021]. 

These qualities of the academic environment can easily make graduate research a struggle, particularly for minoritized students. Succeeding in such a context is impacted by multiple factors, but until recently, such success was largely studied without considering either structural or personal privilege and oppression. Recent reviews of traditional predictors of graduate school success such as undergraduate GPA or GRE scores, have been found to be fairly flawed in terms of determining time to degree or degree completion [@feldon_predictive_2024; @kurysheva_once_2022]. In Feldon et al.’s meta-analysis of 208 studies on the GRE, approximately 62% of all reported effects were nonsignificant. Further,  outcomes related to GPA were very small, accounting for 4% or less of the variance. The GRE’s weakest predictive relationships were with progress towards degree and degree completion, which many would argue are the primary purposes of using the GRE in the admissions selection process. Similarly,GRE scores were not significantly related to attrition. Furthermore, the higher the proportion of POC in a given study’s sample, the poorer the predictive validity of the GRE was. 

In their work on the variables that predict doctoral degree completion, Gittings, Bergman, and Osam [-@gittings_doctoral_2018] noted that 40-60% of graduate students who started a doctoral degree dropped out, most often at the dissertation stage. The authors reviewed evidence on variables that affect degree completion based on Tinto’s [-@tinto_leaving_1994] model of doctoral persistence, which postulates 3 stages in the graduate school journey: transition and adjustment, development of competence (up to and including candidacy/comprehensive exams), and dissertation. For adjustment and transition, early orientation and opportunities for interaction with program faculty and other students are important. Regarding socialization, graduate students have multiple adjustments to make throughout their programs, starting with understanding their university, department, discipline, and program cultures; getting a clear perspective on these norms is strongly related to persistence. Positive interactions with faculty and peers, chances to participate and observe are also relevant. Students need help managing stress and anxiety. Developing goals and balance in personal and academic domains was another area for attention.

In the Developing Competence stage, inter-related systems of community, including familial, social, and academic, interact to either support or hinder the graduate student’s progress. Gittings et al. [-@gittings_doctoral_2018] posit that multiple kinds of support matter (partner/family, advisor/mentor, financial, cohort/peer, employer), and must be sustained over time during this stage in order to allow successful advancement through candidacy/comprehensive exams.

During the final stage - the dissertation experience - the authors note a strong and consistently documented need for students to have “...structured support and clearly established procedures throughout the dissertation process. Doctoral students in multiple studies indicate a need for stronger departmental communication concerning requirements, procedures, and resources connected to completing the doctoral degree.” (@gittings_doctoral_2018, p.33).  The relationship with the doctoral research advisor was also shown to powerfully impact students’ capacity to complete the degree. Another factor shown to impact degree completion was research experience; the more experience students had, the less chance they would be ABD. Students who experience negative research environments are those who are most likely to leave [@kis_leaving_2022]. 

Similarly, Ajjawi et al. [-@ajjawi_what_2018] conducted a “realist” analysis of 42 research environments and identified four key mechanisms that seem critical to creating successful research contexts. These included effective leadership that prioritizes  communication; mentorship; fair resource allocation; and adequate infrastructure regarding funding, equipment, space, administrative support, and technology. The research culture was also important; a positive culture was characterized by collaboration, respect, and support for innovation and creativity. This includes promoting interdisciplinary work, recognizing and valuing diversity, and providing opportunities for professional development and mentorship. Lastly, successful research environments depend on strong and supportive relationships between researchers, including relationships between colleagues, mentors, and trainees. These relationships can provide valuable feedback, guidance, and support for research projects. The authors conclude that successful research environments require attention to both the mechanisms and contextual factors that contribute to their success.
	
Models such as those articulated by Ajjawi et al. [-@ajjawi_what_2018] and Gittings et al. [-@gittings_doctoral_2018] are notable, because laying out the graduate journey in these ways is useful. However, their attention to graduate students’ identity and cultural variables is fairly superficial, and virtually every process mentioned can be more challenging for students with minoritized identities. Graduate school stressors in general have been amply documented. For example, in their review of 34 recent studies on graduate student stress, Cho and Hayter [-@cho_under_2021] confirmed that graduate students experience high levels of stress arising from academic demands, financial pressures, work-life balance, and social isolation, often exacerbated by the nature of graduate education, such as having intense workloads and uncertain futures. The effects of stress on graduate students can be significant and wide-ranging, including negative impacts on mental health, physical health, academic performance, and overall well-being. In their scoping review, Lang and Haugen [-@lang_stress_2023] found that 40% of psychology graduate students met clinical criteria for anxiety or depression. 

One experience that can mitigate some degree of graduate student stress is mentorship [@cannon_relational_2020; @mangione_mentoring_2018]. It should be noted that scholarship in this area is not exclusive to only the research aspects of graduate school.  In this domain as well, traditional models of mentoring fall short for BIPOC students and others with marginalized backgrounds; no-one argues that mentorship is not needed, rather the nature of mentorship must be substantially re-envisioned [@hall_falling_2022; @kim_putting_2021; @cirillo-mccarthy_developing_2022]. As documented in Hall and Liva’s [-@hall_falling_2022] investigation, failures in mentorship left students with a lack of direction, unresolved ambiguity, decreased well-being, and often, additional financial hardship. When mentors lacked commitment to their mentees and/or showed no interest in students’ personal lives, students experienced these relationships as perfunctory and felt treated like employees. Students reported being put off by mentors’ identity-based, microaggressive comments. Power differences and lack of knowledge about academic structures - particularly for international students - made navigating a mentoring relationship difficult. Mentors with strict boundaries who did not provide sufficient information left students confused and alone. Feelings of inadequacy and fears of reprisal or shame kept students from advocating for themselves. Damage to students included stalled progress, decreased self-efficacy and motivation, emotional dysregulation, and fears that their futures would be jeopardized. 

Admittedly, a rather bleak picture of the research environment has been painted here. There are of course, good mentors and some programs that have taken substantive steps towards change, but everyone engaged in the university research process must contend with the historical backdrop of White supremacy culture, whether they do so consciously or not. The voices of minoritized graduate students speak eloquently to the pervasive effects of this environment, often painfully detailing how the White, heterosexist, cis-normative, middle-class/owning class, patriarchal and Eurocentric assumptions of academia manifest in their research endeavors. 

## Experiences of Minoritized Graduate Students

In this section, scholarship that accesses minoritized graduate students’ voices is highlighted. Several researchers have conducted studies with multiple groups of students (e.g. more than a single racial identity) and draw conclusions across these minoritized experiences. This work is summarized first. Following this, studies that feature specific identities are reviewed.

### Studies Using Multiple BIPOC Graduate Student Groups

>In my department (in the sciences) there’s fewer females than males, but in science in general, and I guess the higher you go toward pursuing the PhD, there tend to be fewer, at least, African American females. And so in a way that has actually deterred me  because, I mean, sometimes you feel like you’re the only one. [@levin_graduate_2013, p. 238]

The challenges faced by graduate students, including students of color, are discussed extensively in the literature. These challenges include structural isolation; the significant time commitment required to obtain a degree; stress; and financial concerns including low salaries and high debt [@maton_experiences_2011]. Underrepresented minority graduate students encounter the same challenges as their European American counterparts, along with additional hurdles associated with their ethnic backgrounds. These additional challenges include negative perceptions of academic merit, prejudice and discrimination, alienation and isolation, cultural bias, lack of accurate portrayals, and stereotyping [@curry_systematized_2020; @maton_experiences_2011].

The importance of graduate students' professional and social identity alignment is highlighted, this is noted to be important in graduate students' decision making process about academic career choices [@levin_graduate_2013]. Career choices made by graduate students are influenced by the behaviors of their professors and their own social identities [@levin_graduate_2013]. Graduate students' career choices often do not align with the expectations of their professors, which typically involved pursuing faculty positions. The concept of assonance and dissonance is particularly relevant in understanding the experiences and behaviors of graduate students of color [@levin_graduate_2013] Women of color, for example, experience inherent dissonance in academic spaces due to their race and gender. They often find themselves as anomalies in graduate programs where their racial background sets them apart, and their gender places them in an out-group as it does not align with the dominant identity of professors in the field [@levin_graduate_2013].

The treatment of racial minorities within the dominant STEM culture is also of note in literature. The culture of STEM is noted to give rise to various factors that can influence the retention of underrepresented graduate students, based on the attitudes, mindsets, values, and beliefs prevalent among those in the dominant group [@curry_systematized_2020]. This culture can strengthen (or weaken) internal motivation, positively or negatively influence personal identity development, and significantly impact the perception of advisor and faculty support, as well as the sense of belongingness among peers [@curry_systematized_2020; @miller_values_2020]. Unfortunately, the treatment underrepresented minorities receive from this culture is often disempowering, degrading, and hindering, leading to reactive coping, emotional distress, or even their departure from the field [@curry_systematized_2020]. 

In contrast to the largely negative experiences noted thus far, Koch et. al [-@koch_qualitative_2022] highlighted the existence of microaffirmations and the importance of paying attention to and cultivating microaffirmation in higher education. They define microaffirmations as “subtle or apparently small acknowledgements of a person’s value, culture, identity, and personhood” (p.2885). Interviewing a diverse range of graduate students, they were able to extract several meaningful themes that articulate specific qualities that allow a person to be experienced as microaffirmative. These qualities reflect being non-judgmental, authentic, open and aware, culturally attuned, actively interested in others, willing to advocate, and to grow. It is unknown how widespread instances of microaffirmation may be, and Koch et al. [-@koch_qualitative_2022] are careful to acknowledge that the fact that microaffirmations exist and can be described in no way negates the fact that microaggressions and related hostilities are routinely experienced by minoritized students.

Specific groups of students may experience unique challenges in the graduate research context. Recent scholarship regarding these identity-based groups is reviewed next.

### Graduate Students Who Identify as Asian

>Mostly White guys named John. There are four Johns in our lab. (Vanessa, female?, 3rd year  engineering student, 2nd generation Chinese American)” (@castro_asian_2021, p. 45)

Minorities, including Asian Americans, often report experiencing significant racism and discrimination, which have serious physical and mental health consequences. It is worth noting that anti-Asian sentiment has increased during the COVID-19 pandemic, leading to a surge in xenophobia and hate crimes against Asian Americans [@hwang_demystifying_2021]. Asian American college students are noted to be more likely to experience feelings of hopelessness, depression, and suicidal ideation, which can significantly impact their daily functioning [@mckenzie_campus_2024]. These mental health issues have been linked to factors such as social support and experiences of marginalization. Discrimination, engagement with mental health services, and help-seeking behavior are often studied within the context of higher education for Asian American college students [@mckenzie_campus_2024]. However, there remains a gap in the comprehensive research that captures the diversity of Asian American college students' experiences with mental health. Specific to Asian American graduate students, McKenzie and colleagues [-@mckenzie_campus_2024] found that negative perceptions of campus climate had a detrimental effect on these students’ sense of belonging which in turn, adversely affected their mental health.

The space Asian American women occupy in science, technology, engineering and mathematics (STEM) provides one particular example of the stressors faced by Asian-American graduate students. Castro and Collins [-@castro_asian_2021] explored power and hierarchy within the socially constructed systems of science, race, and gender for Asian American female doctoral students in STEM. The authors note the importance of utilizing the students' experiences as clues to larger social constructs. Asian American women in STEM face challenges related to underrepresentation, limited access to high-ranking positions, and misconceptions about their success and visibility in these fields. Asian American women are often seen as an underrepresented group whose knowledge, values, and practices are not adequately recognized in the dominant knowledge base. They are frequently subjected to the invisible and model minority stereotypes, which portray them as high-achieving students, but who are not considered in discussions about social and educational mobility [@castro_asian_2021]. This misleading perception is reinforced by the visibility of Asian faces in STEM fields, creating the false impression that Asian women are well-represented at the highest levels of STEM industries, academia, and government [@castro_asian_2021].

### Graduate Students Who Identify as Black

>If I could take all my parts with me when I go somewhere, and not have to say to one of them, 'No, you stay home tonight, you won't be welcome,' because I'm going to an all-White party where I can be gay, but not Black. Or I'm going to a Black poetry reading, and half the poets are anti-homosexual or thousands of situations where something of what I am cannot come with me. The day all the different parts of me can come along, we would have what I would call a revolution (Parker, 1999/1978, p. 11 as cited in @minnett_help_2019, p. 211 )

Black graduate students share common characteristics and struggles across disciplines. The literature notes the low percentage of Black faculty that limits the availability of Black women faculty to serve as mentors to Black graduate students [@minnett_help_2019]. Black women doctoral students, especially those attending predominantly White institutions (PWIs), seek mentors who share similar racial and cultural identities and experiences. Furthermore, Black women with racial and social justice-centered perspectives may face additional difficulties in finding supportive mentors due to the lack of ideological alignment based on race, gender, or class alone [@minnett_help_2019]. To navigate graduate school and resist the systematic marginalization faced by Black women in academia, they have developed a system of mutual support through peer mentorship. This peer mentorship serves as a means of survival and a way to collectively resist the marginalization and oppression experienced by Black women within the academy.

Important to note is that the relationship between faculty and students in graduate education is crucial for the success of students in their chosen profession [@brown_interracial_2021]. Minoritized students often have a lack of trust in White professors due to numerous experiences of interpersonal and systemic racism. This mistrust can impede the development of growth-fostering relationships with White allies. This issue is particularly pertinent for Black graduate students, as historical mistrust of White individuals among Black people in the United States is well-documented. Consequently, interracial mistrust, which serves as a protective mechanism for Black individuals, reduces the likelihood of positive interracial academic relationships that could propel Black professionals forward in their careers [@brown_interracial_2021].

While research on mentoring in higher education tends to focus on the undergraduate experience, there is a growing body of literature that examines peer mentoring specifically [@brown_interracial_2021]. Peer mentoring has been found to provide important support, foster a sense of belonging, enhance skill development, and improve student retention, particularly for first-year students [@brown_interracial_2021]. However, it is important to acknowledge that existing conceptions of peer mentoring may not align with the epistemologies of Black women, highlighting the need for tailored approaches that address their specific needs and contexts.   
Working-class African American women doctoral students may face challenges in establishing a sense of belonging within doctoral program culture, even among their peers. Research suggests that an unsupportive academic environment, along with unfamiliarity with the norms of doctoral programs, can contribute to this experience. 

Crumb et al. [-@crumb_illuminating_2020] found that working-class African American women doctoral students at PWIs struggle to connect with other African American women peers due to cultural differences between different socioeconomic statuses. Despite sharing race and gender identities, the distinct social classes create varying educational contexts and access to social capital for affluent and working-class African American women [@crumb_illuminating_2020]. In affluent or middle and upper-class African American communities, the conversion of personal resources into individual achievement and social capital can lead to a higher degree of respect and elitism. This may afford privileges and resources that are not accessible to working-class African American women. The lower socioeconomic standing of working-class African American women can limit their access to these privileges and resources, creating disparities within their social and educational experiences [@crumb_illuminating_2020]. Overall, the combination of unfamiliarity with doctoral program culture and the impact of socioeconomic status can hinder the sense of belonging for working-class Black women doctoral students, even within their own racial and gender communities [@crumb_illuminating_2020]. This highlights the need for greater attention to the experiences and needs of this specific group within doctoral programs, including addressing cultural differences and providing support that considers the intersectionality of race, gender, and socioeconomic status.

### Graduate Students Who Identify as Indigenous

>My family is very supportive, and does not demand a lot of me so that I can focus on school. I take my community responsibilities and graduate work in equal measure, keeping in mind that my work is for my community, not for myself (Unknown). (Heavy Runner-Rioux et al., 2018, p. 37)

One cannot consider the impact of academic culture on Indigenous graduate students without first considering the impact of Indigenous knowledge production on academia. According to Marker [-@marker_indigenous_2019] this consideration first starts with land acknowledgement that the Westernized universities are literally built on Indigenous land. Despite the foundation of academia being rooted on Indigenous land, there is a dearth of acknowledgement not just of the land but of the inclusion of Indigenous knowledge production in academic norms of scholarship. Instead, it is ironically perceived as foreign and “separate” from Western knowledge [@marker_indigenous_2019]. Though there is little research centering the voices of Indigenous students, many important insights about Indigenous student academic experiences can be drawn from a conceptual article written by Marker in 2019. In this article, Marker [-@marker_indigenous_2019] shares his experiences as an indigenous faculty member who mentors Indigenous graduate student researchers and discusses the erasure of Indigenous thought production by the rigid Westernized conceptualization of knowledge production being historically White. The unique challenges that Marker [-@marker_indigenous_2019] shares demonstrate the various contentions that arise when there are “cultural conflicts” between Indigenous and Westernized norms of academic scholarship and highlights ways that faculty and research mentors can help Indigenous students navigate these cultural conflicts.

Runner-Rioux et al. [-@runner-rioux_influence_2018] identified that Indigenous graduate students share some similar challenges as other BIPOC graduate students such as struggling to balance their graduate school and cultural identities. Runner-Rioux et al. [-@runner-rioux_influence_2018] also provides some recommendations for culture-specific protective factors for Indigenous graduate students that aid in their cultural adaptation such as: continuing engagement in activities that foster their tribal and cultural identity (i.e. ceremonies, rituals, elder support) while they are attending graduate school. Marker [-@marker_indigenous_2019] provides some specific examples of how Indigenous students’ cultural identities can be honored in their academic research process by faculty being willing and open to expanding their current understanding of knowledge beyond the strictly Westernized perspective. For example, through mentorship, Marker’s graduate students were able to utilize literary practices in their research that are more common amongst Indigenous peoples that emphasize breath pauses and depict words with images and students were able to honor the influence of their elders in construction of knowledge in their research. In sum, there are ways in which academia’s rigid views on knowledge and scholarship norms in research have been exclusionary of Indigenous thought and there is still much to do in terms of improving the research climate to be more inclusive and celebratory of Indigenous-focused research practices. 

### Graduate Students Who Identify as Latinx

>So, the conflict is when I go home, I am faced with the environment that made me who I once was, and I no longer fit in that environment. I kind of have to deal with that, with my parents and the way they think. I do not think that way anymore. And as much as I want to be there, I know I cannot stay there for very long, so it’s almost like academia de-culturated me from them and it’s a bit of a challenge because I know I can never fully participate in that world again if I’m going to be the person I’m striving to be as an academic. So, the biggest struggle has been shedding the person I used to be. I wanted to cling to my previous identity for a very long time and it was not until I could let go of the old identity that I could reinvent myself and move into a phase where I can actually call myself an emerging scholar. (Jaqueline). [@ramos_conociendo_2020, p. 383]

Latinx graduate students continue to be underrepresented in graduate programs and report experiencing significant challenges in academic spaces. Predominantly, these challenges tend to be linked to integration of their cultural identities with their academic and professional identities in graduate school [@crumb_fostering_2022; @locke_counterstory_2022; @ramos_conociendo_2020]. For example, in qualitative research interviews with Latinx doctoral students, students shared about their experiencing microaggressions from faculty and students, faculty dehumanizing and undervaluing Latinx research populations, feeling isolated and underrepresented, having difficulty navigating White academic spaces, and integrating cultural identities with professional identity [@crumb_fostering_2022; @ramos_conociendo_2020]. When Latinx students are made to feel invisible, underrepresented, and undervalued in research by their peers in academic spaces, it can negatively impact their mental health and access to research opportunities. Latinx graduate students report experiencing anxiety, feeling isolated from both family and academia, and stressors related to academic language expectations and financial stress [@crumb_fostering_2022; @locke_counterstory_2022; @ramos_conociendo_2020]. Further, students have reported experiencing somatic symptoms of these psychological stressors as well (i.e. stomach ulcers and heartburn; @ramos_conociendo_2020). 

The barriers that come with the difficulty of integrating their cultural and academic identities can also make it difficult for Latinx students to find their voice in the research and academic process.  Previous literature on Latinx graduate students demonstrates a process by which these students redefine their identity by finding their own voice and using it to reclaim their power, which allows them to disrupt the academic norms that make them feel like they don’t belong [@locke_counterstory_2022; @ramos_conociendo_2020]. Within this redefinition process Latinx students have identified an important source of support in their families who provide various types of emotional support as they work towards their degree [@crumb_fostering_2022; @locke_counterstory_2022; @ramos_conociendo_2020]. 

### Graduate Students Who Identify as Having a Disability 

>I struggle every single day. I hate how I feel on Adderall. Most people think that Attention Deficit Hyperactivity Disorder is about bouncing off walls and not being able to sit still. This may be true, but it is really about internal chaos. It is lonely and frustrating. Colloquial language about dyslexia tends to obscure the foggy reality of sense-making. I have been ignored, silenced, minimized or left to my own devices to navigate my academic experience. (Emily, November 7th, 2018 as cited in @koren_laissez-faire_2020, p. 21)

Graduate educational spaces pose unique challenges when it comes to accommodating individuals with disabilities. Factors such as student age, professional background, and employment status within the university can further complicate the accommodation process [@koren_laissez-faire_2020]. Scholars argue for a reframing of the dominant narrative that positions disability in relation to ability, known as ableism [@koren_laissez-faire_2020]. Despite the Americans with Disabilities Act (ADA) being in place for three decades, disability studies remain underrepresented in higher education research literature, which can reinforce microaggressive norms that undermine students' persistence. 		

Existing research on psychology graduate students with disabilities has highlighted the numerous challenges they face in their training, as well as their determination to overcome systemic barriers and achieve their professional goals [@lund_investigating_2022]. Despite being academically qualified upon entrance to graduate school, psychology graduate students with disabilities have a higher dropout rate compared to their peers without disabilities, indicating the serious consequences of the lack of accessibility in psychology graduate education [@lund_investigating_2022]. While access for students with disabilities is often thought of in terms of the classroom, graduate students with disabilities also require accommodations in other activities, including graduate student teaching, which is a significant aspect of their training. Many psychology graduate students report difficulties in understanding available accommodations and accessing them effectively, often due to stigma or unfamiliarity with disabilities among faculty [@lund_investigating_2022]. Therefore, it is crucial to increase knowledge about how psychology graduate students with disabilities can be accommodated and supported in their teaching duties. It's important to recognize that these challenges primarily stem from systematic, physical, attitudinal, and programmatic barriers that hinder access, rather than an actual inability to perform the essential functions of their positions.	

There is a need for greater attention to disability issues in higher education research and the importance of creating inclusive and supportive environments that recognize the rights and dignity of disabled students. Efforts should be made to shift the burden of accommodation from students to a collective responsibility shared by all stakeholders in the academic community [@koren_laissez-faire_2020]. Current literature suggests further research that encompasses a broader range of disability types, includes more diverse samples, and employs quantitative methods to complement the qualitative findings. This would enhance the understanding of the experiences of graduate students with disabilities and contribute to the development of more effective support and accommodations in higher education.


### Graduate Students Who Identify as LGBTQ

>Right now, I can think of, maybe, two other trans guys that are in academia and psychology that would be anywhere related enough to what research I do. And they’re at universities at least 1,000 miles away. There’s no real roadmap for me in terms of how [to] be a trans advocator a trans professor (George). (@matsuno_theres_2022, p. 21)

Research on LGBTQ and TNB graduate students has identified that lack of inclusivity in academic environments is a significant stressor for this population. Traditional academic research environments run on cisnormative assumptions that inform non-inclusive policies causing TNB graduate students to feel invisible. TNB students experience anti-trans stigma and discrimination on college campuses that negatively impacts their mental health resulting in higher occurrence of mental health diagnoses such depression and anxiety amongst TNB students [@knutson_advocating_2022; @lipson_gender_2019; @messman_transgender_2019]. Further, TNB-related issues are often omitted from academic curricula, which contributes to the continued erasure or invisibility of TNB challenges in academic spaces. Authors provide the example of using exclusionary language on research demographic forms that perpetuate gender binary language [@knutson_advocating_2022]. This exclusion of TNB students contributes to the current lack of TNB research and biased language used in research on TNB populations. 

TNB graduate students report experiencing challenges in academic climate at macro and micro levels regarding lack of representation and mentorship in psychology, harmful non-inclusive policies, lack of gender affirming care in and outside of the classroom, cisnormativity in course curriculum and research, being misgendered by faculty and peers, and anticipated minority stress which contributes to them having to conceal their TNB identity in academic spaces [@matsuno_theres_2022]. Since TNB-related stigmas and discrimination do not exist in a vacuum, scholars have made recommendations for addressing these challenges at individual and systemic levels  . 

## Summary

Taken together, there are clear patterns in the experiences of marginalized graduate students across identity groups that impact their wellbeing in academic research environments. First, despite educational advancements there is still a lack of representation of marginalized students across graduate disciplines.This lack of representation is a product of an academic system that inherently devalues knowledge production outside of White norms and contributes to invisibility of students in academic research environments. The invisibility then contributes to isolation and difficulty navigating academic culture. Marginalized students are also made to feel isolated and invisible through microaggressions and stereotypes they experience from other students and faculty, which can contribute to their overall mistrust and lowered sense of belonging in academic spaces. 

Just as with other forms of acculturation, the process of integrating one’s intersecting identities can be difficult, especially if the cultural expectations of their environment are that they would let go of their personal and cultural identities to assimilate. This identity integration conflict could be mitigated by cultivating academic research environments that are inclusive and welcoming of students from various cultural backgrounds and making space for them to incorporate their cultural identities in their research environments rather than requiring them to change so that they fit the pre-established White academic norms. . Detailed recommendations to these ends are now presented. 

## Recommendations

As the voices of minoritized graduate students and faculty grow stronger, and cultural shifts following the resurgence of Black Lives Matter and the profound disparities that were laid bare by the COVID pandemic can no longer be ignored, multiple scholar-activists have called for deep-structure changes in academia [@galan_editorial_2021; @haeger_creating_2021; @kent_recommendations_2022; @perez-lopez_ten_2022; @posselt_rigor_2018; @talusan_identity-conscious_2022; @tung_making_2023; @watkins_engaging_2018]. We have clear guidance about what must be shifted and some sense of how to shift it (albeit with varying levels of will and commitment to the process.) These changes revolve around promoting inclusivity, diversity, equity, and ethical research practices, as well as providing support and mentorship for underrepresented groups in academia. They highlight the importance of fostering inclusive and safe research environments; addressing barriers to access and success; and embracing decolonial approaches in the processes of research teaching, mentorship, and the production of knowledge. Specific suggestions are organized from structural  to interpersonal/relational to individual levels. 

While these recommendations are framed largely with an eye towards those in power in the research environment, it is important to acknowledge that many early career professionals (ECPs), especially those with minoritized identities, are simultaneously in positions of power vis a vis their mentees but disempowered in their own academic contexts. For example, the opening vignette of this chapter showcases many of the parallel concerns that ECPs and graduate students share. As a reader, we acknowledge you will come to this chapter situated within your own unique intersections of power, privilege, and oppression. We recognize that more or less may be possible given your standpoint. 

### Structural 

Structural changes represent macro-system level alterations. They reflect a fundamental shift in how research culture is situated and how it would need to function going forward. This is not performative, lip-service, diversity dashboard numbers stuff.  This means the university is operating in a new way that reflects pervasive, consistent, and integrated attention to anti-racism and the related oppression of marginalized persons. In summarizing the literature, five components of structural change in research environments are noted consistently. This list was derived from a thematic analysis of the works of multiple scholars, as they represent substantial agreement on mechanisms of change [@ajjawi_what_2018; @galan_editorial_2021; @haeger_creating_2021; @kent_recommendations_2022; @kis_leaving_2022; @cirillo-mccarthy_developing_2022; @perez-lopez_ten_2022; @posselt_rigor_2018; @talusan_identity-conscious_2022; @tung_making_2023; @watkins_engaging_2018]. 
	
#### Expand Representation  

Expanding representation means promoting diversity and representation at multiple levels of the research process[@haeger_creating_2021; @perez-lopez_ten_2022; @watkins_engaging_2018]. From assuring that minoritized students are admitted to relevant programs, to hiring and retaining diverse faculty/research mentors, to attention to representation on important university research committees, steps must be taken to eliminate underrepresentation. Representation is not just about numbers however; it also means centering marginalized voices to attend to power imbalances within all of these contexts. Who gets to speak, and when? Who is interrupted? Whose ideas are carried forward? Who gets credit for those ideas? Who has decision-making power? Intentional action related to all these elements must be considered. 

### Addressing barriers to access and success

Without real commitment to allocating/reallocating resources, improvement to the research culture will not occur. Financial constraints for graduate students must be addressed; sustainable compensation for their labor and providing a true living wage is paramount. In addition, transparency regarding both financial policies and procedures is needed [@noauthor_equitable_2023].

In parallel, providing institutional support for DEI initiatives is critical. Without it, those who regularly volunteer their time and effort towards structural change will continue to run into roadblocks, suffer from overwork and emotional exhaustion, and make small headway at best. Upper level administrators have difficult decisions to make about allocation of usually scarce resources, and where they choose to put funding will reflect deeply held values; both current and prospective minoritized students and faculty are watching. If equity and accessibility are not clearly evident in structural decisions, people will choose to take their research elsewhere [@cirillo-mccarthy_developing_2022; @perez-lopez_ten_2022]. 

Another recommended avenue to address barriers to access and success is by fostering collaboration and partnerships, including community engagement. This could mean assuring that research is relevant to the community/context in which researchers are embedded, and/or that research projects emerge in active dialogue with community members. Collaborations could also mean creative links across disciplines, in conjunction with corporate partners, or between nations, governments, or non-governmental organizations (NGOs) to name a few possibilities. Such collaborations foster not only information/resource exchange, but may also have the potential in some cases to become funding partners. 

### Implementing bias mitigation strategies

Bias mitigation refers to several strategies that help us surface and then constructively challenge unexamined or unconscious beliefs. Implicit bias, which refers to an unintentional and automatic form of bias that impacts judgments, decisions, and behaviors, is often the target of these interventions [@tung_making_2023]. General techniques for bias mitigation include considering atypical examples, actively challenging our own stereotypes, adopting as much as possible the perspectives of others, and having a plan to remember to consistently disrupt biased thinking in situations where the stakes are high and one might   be more prone to bias (e.g. job interviews or admissions decisions). 

Bias mitigation at the structural level means that there are enforceable expectations that administrators, faculty, and staff receive bias training. Participating in a general implicit-bias workshop may be a good start, though there are specific trainings for those who are doing admissions work and/or hiring, two crucial areas that are prone to distortions. Structural level bias mitigation also occurs when there are expectations to incorporate diversity, equity and inclusion (DEI) into curriculum and training. Engaging in decolonial and anti-racist approaches to teaching and research are key here - and should be integrated into faculty tenure and promotion criteria so that accountability is better ensured. Graduate programs should consider using holistic admissions procedures including dropping the use of the GRE [@feldon_predictive_2024]. 

### Research Integrity and Open Science

There is significant alignment between the principles of open science and shifting the structure of traditional research environments to be more equitable. Open science explicitly values a diversity of perspectives including indigenous knowledge, and a host of processes that create transparency and access, such as open methodology, sources, data, and review [@noauthor_open_2018; @unesco_unesco_2021. Given that part of White supremacy culture is hoarding power (Okun, 2021), including controlling information and assuming that those with less power don’t need to know (or can’t understand), the adoption of open science practices would represent a clear anti-racist position. 

Many of the critiques that have come forward regarding how science is conducted and its ties to racism (e.g. @buchanan_upending_2021) are now detailed as better transparency reveals the extent to which scholars of color and those with other minoritized identities are underrepresented in all aspects of research production and dissemination, including grant funding, publication, editorships, and peer review positions. Therefore, universities should consider grounding research policies and procedures in open science, expanding definitions of what is considered viable research in tenure and promotion decisions and for graduate students’ thesis and dissertation projects. As with anti-bias training, structural support for faculty researchers to learn how to make the shift to an open science perspective is needed.

Promoting research integrity and ethical practices is also a component of open science [@noauthor_open_2018].  It is notable that in several studies we reviewed, graduate students’ experiences with unethical research advisors and faculty were contributors to student distress and attrition [@hall_falling_2022; @kis_leaving_2022]. Research faculty who act in an unethical manner, including but not limited to being microaggressive and dismissive of minoritized students’ ideas and work, should have meaningful and effective remediation of their behavior; if unimproved, there should be consequences.  

### Regularly assess

Last but not least, structural efforts towards improving the research environment should be evaluated in an ongoing fashion [@tung_making_2023]. This entails routinely collecting and analyzing data on diversity, equity, and inclusion at multiple levels in the institution. Regular climate surveys and assessments should be conducted. The voices of minoritized graduate students and pre-tenure faculty should be central in these efforts; if they are not experiencing the benefits of structural change in their daily lives as researchers, the system has not shifted sufficiently. Well-intentioned efforts often lose momentum, drift, or get derailed. Thoughtful assessment practices, combined with actionable shifts using evaluation data, are critical. As with other forms of structural change, thorough assessment takes resources. A fully resourced, intentional framework for determining if a program, department, or institution’s research environment is supportive and welcoming for all is ideal [@galan_editorial_2021].

In summary, structural changes in the research culture set the groundwork for effective implementation of all other recommendations. While individuals can attempt to carry out strategies and interpersonal processes independent of structural change, it will always be more challenging to be effective if constantly fighting an unsupportive backdrop. That said, there are several recommendations for enhancing the interpersonal environment in research settings. 

## Relational/Mentoring

The scholarship we reviewed was clear that good mentorship is essential to the research endeavor, and lack thereof generates multiple problems, including contributions to attrition. Given the adverse experiences that exist for marginalized students across micro and macro levels, mentorship is extremely important. Due to lack of representation there is also a lack of mentorship for marginalized students. Mentorship has the potential to aid in directly addressing the adverse experiences of marginalized students and providing them with safe spaces as they navigate the integration of intersecting identities . It is critical that we realize just how profoundly relational good mentoring is [@cannon_relational_2020]. This is in contrast to the typical view that the importance of a research mentor lies in their content expertise [@mangione_mentoring_2018]. Realistically, content can be gleaned from multiple resources, both virtual and in-person. But the experience of someone else caring about you, taking time to collaboratively navigate challenges with you, taking an interest in who you are and how your context is impacting you, thinking about you when you aren’t in an actual appointment together - those aspects of mentoring are unavailable in databases or podcasts or journal instructions-to-authors. We distilled six key processes of socially just mentoring from our review of the literature. 

### Relationship Building

Build positive relationships with mentees based on trust, respect, and understanding. Directly acknowledge and address power dynamics and create a safe space for interpersonal exchanges. Strong and supportive relationships are characterized by several well-defined components, including frequent interactions, open communication, personal investment, and reliable follow-through. Provide clear expectations and structured guidance. Responsive, available, and culturally-sensitive personal support is invaluable [@ajjawi_what_2018; @haeger_creating_2021; @cirillo-mccarthy_developing_2022].

### Provide Support for Mental Health and Wellness 
	 
Prioritize self-care for both your mentees and yourself [@cho_under_2021; @kent_recommendations_2022; @mangione_mentoring_2018; @perez-lopez_ten_2022]. It is difficult if not impossible to create a sense of well-being for others if you’re not able to do so for yourself; with this comes the recognition that care must be a reciprocal process. Reflect on the emotional and cognitive experiences of mentees within the mentoring relationship to try to imagine and empathize with what they might be going through. Provide active reassurance and positive feedback to counter imposter syndrome and isolation. Normalize the challenges of graduate school and doing research so that students don’t feel “less than” for being uncertain or not having all the answers. Know your campus and community resources for professional support. Frequent microaffirmations [@koch_qualitative_2022] may go a long way towards buffering the stressors of conducting research. 

### Individualize your Mentorship
	
Recognize the unique needs of students and the importance of providing individualized support [@cirillo-mccarthy_developing_2022]. Customize mentorship experiences to align with individual preferences, cultural ways of being, and intersecting identities; this will mean taking the time to get to know your mentees and to be patient while creating safety and trust in order to have such conversations. Recognize that you may not know the ways in which a students’ culture impacts their research work and be open to learning about that (see literature on cultural humility and liberatory mentoring; e.g. @malone_liberatory_2022).  Address specific challenges that your mentee may face. Be willing to address both mentees’ academic and personal goals.

###	Be an Active Advocate

Being an active advocate means challenging the status quo and going beyond declaring allyship to actively manifesting it by using your power to address injustice [@kim_putting_2021]. If you have them, share strategies of resistance. Assist mentees in leveraging the academic resources available to them. This means “walking the walk” to assist graduate students with whom you’re working to navigate not only your research lab or team, but their program, department, and university administrative offices, policies, procedures, and politics. Arguably, much of this might be done proactively, but if not, as needs arise. It can also mean advocating for student resources. An example of this was demonstrated in the opening story of this chapter, where the research mentor navigated academic norms and biases alongside her dissertation student and offered additional support through check-ins and debriefs following difficult roadblocks in the research process. 
	
### Be Real
	
Embrace relational openness. Share vulnerability and at a personal level; let mentees know who you are beyond your professional role [@kim_putting_2021]. We’re not suggesting wild, unethical, unboundaried sharing here, but letting your research mentees know in some small ways that you are human. For example, you might consider sharing some of your own mistakes and missteps and a bit about your own professional journey (as long as you are not abusing power and holding court by telling long narcissistic stories). We’re all entitled to our privacy and individual differences in our tolerance for self-disclosure, but within your personal limits, showing up authentically is often appreciated. In a related vein, show genuine interest in mentee’s families, culture, and personhood. Too many graduate students have reported feeling like an anonymous cog in someone’s research machine [@hall_falling_2022], which is dehumanizing and demeaning. 

###	Expand Mentorship Activities
	
Broaden mentoring activities beyond academia to include discussions on career paths, professional identity development, work-life balance, and self-care [@cho_under_2021; @kent_recommendations_2022; @mangione_mentoring_2018; @talusan_identity-conscious_2022]. Help to create mentoring networks, both within the bounds of your program and outside of it in the community and/or other relevant professional spheres. Many graduate students have questions about their future directions and options, and may welcome the chance to discuss them,as well as to connect with relevant contacts in their areas of interest. Discussions about the realities of life after graduation can also be potentially valuable, and you can assist in setting students up for success by sharing realities, challenges, rewards, and other insider knowledge you may have. Modeling work-life balance and self-care, along with active encouragement for these activities, can also be considered an important component of mentoring.  

## Personal: Those in Positions of Power

If you are doing any or all of these tasks: teaching research courses, serving as a thesis or dissertation chair, running a research lab, and/or working on a grant with research assistants -  you are uniquely positioned to make a shift in the research culture of your program, department, and school. If you are already actively practicing anti-racist and social justice-informed science, kudos! If you aren’t, there are several steps in what is an ongoing journey. 														

Most foundational is to start with an openness to self-reflection and self-awareness, exploring your own identities, biases, power, privileges and areas of marginalization. That exploration will most likely be facilitated by engaging in ongoing education to understand personal, relational, and structural inequities [@galan_editorial_2021; @perez-lopez_ten_2022; @talusan_identity-conscious_2022; @tung_making_2023; @watkins_engaging_2018]. There are numerous resources available to start this journey; the important thing is to begin. 								

One of the most commonly recommended sources of awareness is anti-bias training. While mentioned earlier as important in structural change, in the end it comes down to your willingness to participate in such training and to take it seriously. Similarly, actively incorporating decolonial and anti-racist pedagogy in your teaching and research is another key element in making the research environment more welcoming for minoritized students [@kent_recommendations_2022; @perez-lopez_ten_2022; @posselt_rigor_2018; @talusan_identity-conscious_2022]. Resources are readily available here as well. There is also training available specific to mentoring that may be valuable. 			

Ultimately, our everyday interactions with our students and colleagues should reflect cultural humility and a conscious resistance to traditional behavior patterns [@tung_making_2023]. Entrenched ways of thinking about our research endeavors - what is important, by what criteria it is evaluated, the role of students in the process, how much and what we should communicate about - must be continually re-examined. Catching ourselves in the act of recreating past harms and then choosing to name them out loud, apologize, and do something different that is more supportive and more equitable is likely to be a common occurrence as we learn to participate in a healthier, more inclusive, and more open research culture. 

## Personal: Minoritized Students

Across all minoritized graduate student populations discussed in this chapter, research literature points to the importance of several cultural protective factors that can aid in students’ sense of belonging and support in an academic research setting. One overarching theme is that marginalized students may benefit from intentional efforts to feel supported in their process of integrating their cultural values and their identity as graduate students. For example, past research has demonstrated ways that graduate students can continue to honor their cultural identity during their graduate studies by integrating these values into the research process and cultivating safe spaces on campus [@knutson_advocating_2022]. Students in qualitative studies have expressed this experience of feeling like they are expected to assimilate into academic culture, which means not being able to hold onto their own cultural values [@crumb_fostering_2022]. Thus, graduate students are encouraged to seek ways that they can utilize and apply their cultural values as sources of support directly applied to their research process. For example, qualitative studies have demonstrated that when Latinx students are able to embrace familismo cultural values while in graduate school they may experience a more inclusive and culturally competent academic environment, which can also aid in their professional and cultural identity development through embracing. Additionally, students are encouraged to seek and cultivate safe supportive spaces at their academic institutions that can bring students with similar identities and values together rather than feeling isolated. This could look like creating cross-discipline student groups that meet periodically for research talks or general graduate student support.

Runner-Rioux et al. [-@runner-rioux_influence_2018] provide some recommendations for culture-specific protective factors for Indigenous graduate students that aid in their cultural adaptation such as: continuing engagement in activities that foster their tribal and cultural identity (i.e. ceremonies, rituals, elder support) while they are attending graduate school. Marker [-@marker_indigenous_2019] provided specific examples of how Indigenous students’ cultural identities can be honored in their academic research process by faculty being willing and open to expanding their current understanding of knowledge beyond the strictly Westernized perspective. For example, through mentorship, Marker’s graduate students were able to utilize literary practices in their research that are more common amongst Indigenous peoples that emphasize breath pauses and depict words with images and students were able to honor the influence of their elders in construction of knowledge in their research. In the IRB story shared at the beginning of this chapter, the research mentee was supported in her efforts to study a vulnerable marginalized population through mentorship that was tailored to her individual needs rather than being expected to assimilate mainstream White academic research culture.
	
Other researchers have identified several personal actions that can work to the benefit of minoritized graduate students. For example, Curry and DeBoer [-@curry_systematized_2020] found that centering one’s internal motivation for pursuing a higher degree helped students to persist in their programs. In a related vein, Miller and Orsillo [-@miller_values_2020] found that to the extent that underrepresented students in graduate school could live their values on a regular basis provided a significant buffer against the stressors of the research environment. 

## Conclusion

Well, there’s a lot of changes needed to improve academic research environments for minoritized students! The research provided above shows that we (academia) know how to do it, but those in power need to have the will to do it and to put substantial resources behind it. The whole point of doing research is to construct novel ideas and knowledge, but when done stringrently within the confines of White academia, we actually limit the kinds of knowledge we can produce and harm minoritized students in the process. We all need to examine our biases and be open to real connection with students and not to assume we know everything—or anything. Be culturally humble. Continuously reflect. Challenge the status quo. Color outside of the lines. Allow yourself and others freedom to expand beyond the limitations of historically White academic norms. You just might be surprised by what you find! 



## Suggestions for Practice, Further Learning, and/or Conversation

*For Students*: 

* Small group discussion 1: Break into groups of 4-5 and discuss how your own cultural beliefs, identities, and family background influence your view of research - how to do it, why to do it, if to do it, what to study? 
* Small group discussion 2:  Break out into groups of 4- 5 focusing on two distinct perspectives: that of the faculty member and the student. The goal is to explore how from each perspective individuals identities can significantly impact and influence the research process.
    + Group 1 (Faculty Member Perspective):
        - How might the faculty members' identities impact their research proposal, interactions with IRB, and overall experience?
        - How could this experience have affected the faculty member’s relationships with students and faculty/colleagues?
    + Group 2 (Student Perspective)
        - How might the students' identities have influenced their willingness to participate in the research?
        - What impact could the student’s identity have on their trust in the faculty members' guidance? 

Individually or with another student or two: Pick a research-related document in your program, department, college, graduate school or university (e.g. a Student Handbook, Graduate School guidelines for dissertations, or policies about what is considered timely progress, etc.). Critique it from your own perspective(s) as a student(s) with your unique culture and identity. If you feel brave, share what you found with someone you trust who might have the power to change it. 


*For Faculty*: 

* Make a timeline tracing key points in your academic history as related to the research process. What were the values, assumptions, and behaviors that were reinforced and rewarded around those crucial milestones? Using Okun’s (2021) document, identify any components in your research experience that might have reflected White supremacy culture. 
* Jot down the steps in your typical approach to working with graduate students on their research. Note what your expectations are about what the student should and should not be doing at each step. Make sure to include your pet peeves. Then list 3 students you have worked with who have different backgrounds from you and from each other. For each student and at each step, consider the following: 
    + What privileges do I have (i.e. things I don’t have to worry about) in comparison to my student? 
    + What ideas do I have about working with this student based on their identities and cultural background? Check to see if any of these reflect stereotypes.
    + What do I assume this student should already know/know how to do? Consider to what extent those things may or may have been in the student’s control during their educational history to date. 


